import { useCallback, useEffect, useState } from "react";
import "./AdminApp.css";

const API = import.meta.env.VITE_API_BASE || "http://127.0.0.1:8000";
const NAV = ["Overview", "Jobs", "Contestants", "Infrastructure", "Failures", "Tournament", "Event mode", "Audit"];
const pretty = (value) => value == null ? "—" : typeof value === "number" ? value.toLocaleString() : value;

export default function AdminApp() {
  const [auth, setAuth] = useState(false), [password, setPassword] = useState(""), [error, setError] = useState(""), [csrfToken, setCsrfToken] = useState("");
  const [tab, setTab] = useState("Overview"), [data, setData] = useState(null), [jobs, setJobs] = useState([]), [contestants, setContestants] = useState([]);
  const [failures, setFailures] = useState([]), [audit, setAudit] = useState([]), [selected, setSelected] = useState(null), [filter, setFilter] = useState({ type: "", status: "", team: "", error_type: "", created_after: "", created_before: "" }), [tournament, setTournament] = useState(null);
  const [event, setEvent] = useState(null), [detail, setDetail] = useState(null), [busy, setBusy] = useState(false);
  const request = useCallback(async (path, options = {}) => {
    const response = await fetch(`${API}/api/admin${path}`, { credentials: "include", ...options, headers: { "Content-Type": "application/json", ...(csrfToken ? { "X-Admin-CSRF": csrfToken } : {}), ...options.headers } });
    const body = await response.json().catch(() => ({}));
    if (!response.ok) throw new Error(body.detail || `Request failed (${response.status})`);
    return body;
  }, [csrfToken]);
  const refresh = useCallback(async () => {
    if (!auth) return;
    try {
      const m = await request("/metrics"); setData(m); setEvent(m.event);
      if (tab === "Jobs") { const query={...filter}; for (const key of ["created_after","created_before"]) if(query[key])query[key]=new Date(query[key]).toISOString(); setJobs((await request(`/jobs?${new URLSearchParams(Object.fromEntries(Object.entries(query).filter(([,v]) => v)))}`)).jobs); }
      if (tab === "Contestants") setContestants((await request("/contestants")).contestants);
      if (tab === "Failures") { const f = await request("/failures"); setFailures(f.failures); setJobs(f.jobs); }
      if (tab === "Audit") setAudit((await request("/audit")).actions);
      if (tab === "Tournament") setTournament(await request("/tournament"));
    } catch (e) { setError(e.message); if (e.message.includes("login") || e.message.includes("session")) setAuth(false); }
  }, [auth, filter, request, tab]);
  useEffect(() => {
    let cancelled = false;
    fetch(`${API}/api/admin/session`, { credentials: "include" })
      .then(async (response) => { if (!response.ok) throw new Error("No active organizer session."); return response.json(); })
      .then((session) => { if (!cancelled) { setCsrfToken(session.csrfToken); setAuth(true); } })
      .catch(() => { /* No active session leaves the login form available. */ });
    return () => { cancelled = true; };
  }, []);
  useEffect(() => {
    if (!auth) return undefined;
    const initial = window.setTimeout(() => { void refresh(); }, 0);
    const timer = window.setInterval(() => { void refresh(); }, 5000);
    return () => { window.clearTimeout(initial); window.clearInterval(timer); };
  }, [auth, refresh]);
  async function login(e) { e.preventDefault(); setBusy(true); setError(""); try { const session=await request("/login", { method: "POST", body: JSON.stringify({ password }) }); setCsrfToken(session.csrfToken); setPassword(""); setAuth(true); } catch (e2) { setError(e2.message); } finally { setBusy(false); } }
  async function logout() { try { await request("/logout", { method: "POST" }); } catch { /* The session may have expired already. */ } setAuth(false); setCsrfToken(""); setData(null); }
  async function action(path, confirmation) { if (!window.confirm(`${confirmation} this change?`)) return; try { await request(path, { method: "POST", body: JSON.stringify({ confirmation }) }); await refresh(); } catch (e) { setError(e.message); } }
  async function saveEvent() { if(!window.confirm(`Apply ${event.mode} event settings?`))return; try { await request("/event", { method: "PUT", body: JSON.stringify(event) }); await refresh(); } catch (e) { setError(e.message); } }
  async function openTeam(name) { try { setDetail(await request(`/contestants/${encodeURIComponent(name)}`)); } catch(e) { setError(e.message); } }
  if (!auth) return <main className="admin-login"><div className="login-card"><img className="admin-brand-mark" src="/farmcraft-mark.svg" alt="" /><span className="admin-kicker">FARMCRAFT / ORGANIZER ACCESS</span><h1>Control Room</h1><p>Sign in with the event organizer credential.</p><form onSubmit={login}><label>Organizer password<input autoFocus type="password" value={password} onChange={e => setPassword(e.target.value)} /></label><button disabled={busy}>{busy ? "Checking…" : "Enter Control Room"}</button></form>{error && <p className="admin-error">{error}</p>}</div></main>;
  const worker = data?.workers || {}, queues = data?.queues || {};
  return <div className="control-room"><header className="admin-header"><div className="admin-brand-lockup"><img src="/farmcraft-mark.svg" alt="" /><div><span className="admin-kicker">FARMCRAFT · OPERATIONS</span><h1>Control Room</h1></div></div><div className="admin-header-status"><span className={`health-pill ${String(data?.systemStatus || "loading").toLowerCase()}`}>{data?.systemStatus || "CONNECTING"}</span><span className="mode-pill">{data?.event?.mode || "EVENT"}</span><button className="quiet-button" onClick={logout}>Sign out</button></div></header>
    <aside className="admin-sidebar">{NAV.map(n => <button className={tab === n ? "selected" : ""} onClick={() => { setTab(n); setSelected(null); }} key={n}>{n}</button>)}<small>LIVE EVENT SYSTEM</small></aside>
    <main className="admin-main">{error && <div className="admin-error banner">{error}<button onClick={() => setError("")}>×</button></div>}
      {tab === "Overview" && <><div className="panel-title"><div><span className="admin-kicker">LIVE TELEMETRY</span><h2>Event overview</h2></div><span className="refresh-mark">AUTO REFRESH · 5 SEC</span></div><div className="metric-grid">{[["CONTESTANTS",data?.contestants],["BOT VERSIONS",data?.submissions],["OFFICIAL ENTRIES",data?.officialTeams],["EVALUATED",data?.evaluatedTeams],["QUEUED",data?.queued],["RUNNING",data?.running],["COMPLETED",data?.completed],["FAILED",data?.failed]].map(([l,v]) => <Metric key={l} label={l} value={pretty(v)} />)}</div><div className="overview-grid"><section className="admin-panel"><h3>Dependency health</h3>{Object.entries(data?.health || {}).map(([name,status]) => <StatusRow key={name} name={name} status={status} />)}<StatusRow name="worker capacity" status={worker.offline ? "degraded" : worker.total ? "healthy" : "unknown"} value={`${worker.busy || 0} BUSY / ${worker.total || 0} SEEN`} /></section><section className="admin-panel"><h3>Queue pressure</h3>{Object.entries(queues).map(([name,q]) => <div className="queue-row" key={name}><b>{name.toUpperCase()}</b><span>{q.queued} queued</span><span>{q.running} running</span><span>{q.oldestWaitSeconds == null ? "—" : `${q.oldestWaitSeconds}s wait`}</span><em>{q.paused ? "PAUSED" : "OPEN"}</em></div>)}</section></div><div className="metric-grid metric-grid-small"><Metric label="AVG JOB RUNTIME" value={data?.averageJobRuntime == null ? "—" : `${data.averageJobRuntime}s`} /><Metric label="P95 JOB RUNTIME" value={data?.p95JobRuntime == null ? "—" : `${data.p95JobRuntime}s`} /><Metric label="AVG QUEUE WAIT" value={data?.averageQueueWait == null ? "—" : `${data.averageQueueWait}s`} /><Metric label="FAILURE RATE" value={`${((data?.failureRate || 0) * 100).toFixed(1)}%`} /><Metric label="API P95" value={data?.api?.p95LatencyMs == null ? "—" : `${data.api.p95LatencyMs}ms`} /></div></>}
      {tab === "Jobs" && <><div className="panel-title"><div><span className="admin-kicker">EXECUTION QUEUE</span><h2>Jobs</h2></div><div className="filters"><select value={filter.type} onChange={e => setFilter({...filter,type:e.target.value})}><option value="">All types</option>{["sandbox","official","tournament"].map(x=><option key={x}>{x}</option>)}</select><select value={filter.status} onChange={e => setFilter({...filter,status:e.target.value})}><option value="">All states</option>{["queued","running","completed","failed","cancelled"].map(x=><option key={x}>{x}</option>)}</select><input aria-label="Filter team" placeholder="Team" value={filter.team} onChange={e=>setFilter({...filter,team:e.target.value})}/><select aria-label="Filter failure type" value={filter.error_type} onChange={e=>setFilter({...filter,error_type:e.target.value})}><option value="">All failure types</option>{["CONTESTANT_SYNTAX_ERROR","CONTESTANT_RUNTIME_ERROR","CONTESTANT_TIMEOUT","INVALID_ACTION","ENGINE_FAILURE","WORKER_FAILURE","DATABASE_FAILURE","REDIS_FAILURE","STORAGE_FAILURE","INFRASTRUCTURE_TIMEOUT"].map(x=><option key={x}>{x}</option>)}</select><input aria-label="Created after" type="datetime-local" value={filter.created_after} onChange={e=>setFilter({...filter,created_after:e.target.value})}/><input aria-label="Created before" type="datetime-local" value={filter.created_before} onChange={e=>setFilter({...filter,created_before:e.target.value})}/></div></div>{selected ? <JobDetail job={selected} onBack={()=>setSelected(null)} onRetry={()=>action(`/jobs/${selected.id}/retry`,`RETRY`)} onCancel={()=>action(`/jobs/${selected.id}/cancel`,`CANCEL`)} /> : <div className="table-wrap"><table><thead><tr>{["JOB / TEAM","TYPE","STATE","CREATED","WAIT","RUNTIME","WORKER","PROGRESS","FAILURE"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{jobs.map(j=><tr key={j.id} onClick={()=>setSelected(j)}><td><b>{j.id.slice(0,8)}</b><small>{j.team || "Arena system"}</small></td><td>{j.type}</td><td><span className={`state ${j.status}`}>{j.status}</span></td><td>{j.createdAt?.replace("T"," ")}</td><td>{j.queueWaitSeconds == null ? "—" : `${j.queueWaitSeconds}s`}</td><td>{j.runtimeSeconds == null ? "—" : `${j.runtimeSeconds}s`}</td><td>{j.worker || "—"}</td><td>{j.progressTotal ? `${j.progressCurrent}/${j.progressTotal}` : "—"}</td><td>{j.errorKind || "—"}</td></tr>)}</tbody></table>{!jobs.length && <p className="empty-admin">No matching jobs.</p>}</div>}</>}
      {tab === "Contestants" && <><div className="panel-title"><div><span className="admin-kicker">TEAM ROSTER</span><h2>Contestants</h2></div></div>{detail ? <section className="admin-panel"><button className="quiet-button" onClick={()=>setDetail(null)}>← All teams</button><h3>{detail.team}</h3><p>{detail.submissions?.length} versions · {detail.jobs?.length} recent jobs</p><div className="table-wrap"><table><thead><tr><th>VERSION</th><th>VALIDATION</th><th>UPLOADED</th><th>SANDBOX</th><th>OFFICIAL SCORE</th></tr></thead><tbody>{detail.submissions?.map(s=><tr key={s.id}><td>v{s.version}{s.is_active ? " · ACTIVE" : ""}</td><td>{s.validation_status}</td><td>{s.created_at}</td><td>{s.sandbox_score ?? "—"}</td><td>{s.official_score ?? "—"}</td></tr>)}</tbody></table></div></section> : <div className="table-wrap"><table><thead><tr>{["TEAM","LATEST","VALIDATION","SANDBOXES","OFFICIAL","RATING","RANK","ACTIVITY"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{contestants.map(c=><tr key={c.team} onClick={()=>openTeam(c.team)}><td><b>{c.team}{c.isRehearsal&&<small>REHEARSAL</small>}</b></td><td>{c.latestVersion ? `v${c.latestVersion}` : "—"}</td><td>{c.validation}</td><td>{c.sandboxCount}</td><td>{c.officialStatus}</td><td>{c.rating ?? "—"}</td><td>{c.rank ? `#${c.rank}` : "—"}</td><td>{c.lastActivity}</td></tr>)}</tbody></table></div>}</>}
      {tab === "Infrastructure" && <><div className="panel-title"><div><span className="admin-kicker">SERVICE STATUS</span><h2>Infrastructure</h2></div></div><div className="overview-grid">{Object.entries(data?.health || {}).map(([name,status])=><section className="admin-panel" key={name}><StatusRow name={name} status={status}/><small>Probed from the API service</small></section>)}</div><section className="admin-panel"><h3>Workers <span className="subtle">{worker.busy || 0} busy · {worker.idle || 0} idle · {worker.offline || 0} offline</span></h3><div className="table-wrap"><table><thead><tr><th>WORKER ID</th><th>STATE</th><th>LAST HEARTBEAT</th><th>CURRENT JOB</th><th>COMPLETED</th><th>FAILED</th></tr></thead><tbody>{worker.items?.map(w=><tr key={w.id}><td>{w.id}</td><td>{w.status}</td><td>{w.lastHeartbeat}</td><td>{w.currentJobId || "—"}</td><td>{w.jobsCompleted}</td><td>{w.jobsFailed}</td></tr>)}</tbody></table>{!worker.items?.length&&<p className="empty-admin">No worker heartbeat received yet.</p>}</div></section><section className="admin-panel"><h3>Queue controls</h3>{Object.entries(queues).map(([name,q])=><div className="control-row" key={name}><b>{name.toUpperCase()}</b><span>{q.queued} queued · {q.running} running</span><button onClick={()=>action(`/queues/${name}/${q.paused?"resume":"pause"}`,q.paused?"RESUME":"PAUSE")}>{q.paused?"Resume":"Pause"}</button></div>)}</section></>}
      {tab === "Failures" && <><div className="panel-title"><div><span className="admin-kicker">FAULT TRIAGE</span><h2>Failures</h2></div></div><div className="overview-grid">{failures.map(f=><Metric key={f.type} label={f.type} value={f.count} hint={`Latest ${f.latest || "—"}`} />)}</div><div className="table-wrap"><table><thead><tr><th>JOB</th><th>TEAM</th><th>TYPE</th><th>ERROR CLASS</th><th>DETAIL</th><th>WHEN</th></tr></thead><tbody>{(awaitSafeJobs(jobs, data)).map(j=><tr key={j.id}><td>{j.id?.slice(0,8)}</td><td>{j.team}</td><td>{j.type}</td><td>{j.errorKind}</td><td>{j.error}</td><td>{j.completedAt}</td></tr>)}</tbody></table></div></>}
      {tab === "Tournament" && tournament && <><div className="panel-title"><div><span className="admin-kicker">BRACKET OPERATIONS</span><h2>Tournament control</h2></div><span className={`state ${tournament.status}`}>{tournament.status}</span></div><div className="overview-grid"><section className="admin-panel"><h3>Current event</h3><div className="status-row"><b>Mode</b><em>{event?.mode || "—"}</em></div><div className="status-row"><b>Participants</b><em>{tournament.playersCount || 0}</em></div><div className="status-row"><b>Round</b><em>{tournament.currentRound || 0}</em></div><div className="status-row"><b>Queue / status</b><em>{tournament.message || "—"}</em></div>{tournament.champion && <div className="champion-admin"><span>CHAMPION</span><strong>{tournament.champion.username}</strong></div>}<div className="tournament-actions"><button onClick={()=>action("/tournament/qualifiers","LOAD QUALIFIERS")}>Load top qualifiers</button><button className="primary-action" onClick={()=>action("/tournament/start","START TOURNAMENT")}>Queue tournament</button><button className="danger-button" onClick={()=>action("/tournament/reset","RESET TOURNAMENT")}>Reset bracket</button></div><small>Launch/reset actions require a confirmation. Tournament work is dispatched to the priority queue.</small></section><section className="admin-panel"><h3>Current matches</h3>{(tournament.currentMatches || []).map((match,index)=><div className="queue-row" key={match.id || index}><b>{match.player1}</b><span>{match.status}</span><span>{match.player2}</span><em>{match.winner ? `WINNER ${match.winner}` : "—"}</em></div>)}{!tournament.currentMatches?.length&&<p className="empty-admin">No active matches.</p>}</section></div><section className="admin-panel"><h3>Bracket history</h3>{(tournament.roundsHistory || []).map(round=><div className="queue-row" key={round.round}><b>ROUND {round.round}</b><span>{round.matches?.length || 0} matches</span><span>{round.advancing?.length || 0} advancing</span><em>{round.byePlayer || "NO BYE"}</em></div>)}{!tournament.roundsHistory?.length&&<p className="empty-admin">No completed rounds.</p>}</section></>}
      {tab === "Event mode" && event && <><div className="panel-title"><div><span className="admin-kicker">EVENT CONFIGURATION</span><h2>Event mode</h2></div></div><section className="admin-panel event-panel"><label>Operating mode<select value={event.mode} onChange={e=>{const mode=e.target.value;setEvent({...event,mode,...({DEVELOPMENT:{uploadsEnabled:true,sandboxEnabled:true,officialEnabled:true,tournamentEnabled:false},QUALIFICATION:{uploadsEnabled:true,sandboxEnabled:true,officialEnabled:true,tournamentEnabled:false},TOURNAMENT:{uploadsEnabled:true,sandboxEnabled:false,officialEnabled:false,tournamentEnabled:true},MAINTENANCE:{uploadsEnabled:false,sandboxEnabled:false,officialEnabled:false,tournamentEnabled:false}[mode]})});}}>{["DEVELOPMENT","QUALIFICATION","TOURNAMENT","MAINTENANCE"].map(x=><option key={x}>{x}</option>)}</select></label>{[["uploadsEnabled","Allow uploads"],["sandboxEnabled","Allow sandbox jobs"],["officialEnabled","Allow official submissions"],["tournamentEnabled","Allow tournament launch"]].map(([key,label])=><label className="toggle-row" key={key}>{label}<input type="checkbox" checked={!!event[key]} onChange={e=>setEvent({...event,[key]:e.target.checked})}/></label>)}<button className="primary-action" onClick={saveEvent}>Save event settings</button><p>Changes are written to the shared event configuration and applied to contestant submission endpoints.</p></section><section className="admin-panel event-panel rehearsal-panel"><span className="admin-kicker">ISOLATED TEST DATA</span><h3>Event rehearsal</h3><p>Populate 2–100 synthetic teams. Rehearsal entries stay out of the public leaderboard.</p><div className="rehearsal-actions"><input id="rehearsal-count" type="number" min="2" max="100" defaultValue="100"/><button onClick={async()=>{const count=Number(document.getElementById("rehearsal-count").value);if(!window.confirm(`Create ${count} synthetic rehearsal teams?`))return;try{const out=await request("/rehearsal/seed",{method:"POST",body:JSON.stringify({count})});setError(`Created ${out.created} isolated rehearsal teams.`);await refresh();}catch(e){setError(e.message);}}}>Create synthetic teams</button><button onClick={()=>action("/rehearsal/queue","QUEUE REHEARSAL")}>Queue fake sandbox surge</button><button className="danger-button" onClick={()=>action("/rehearsal/reset","RESET REHEARSAL")}>Reset rehearsal data</button></div><p>Queue surge requires fake simulation enabled on a local or staging environment. Cleanup waits for queued/running rehearsal jobs to finish.</p></section></>}
      {tab === "Audit" && <><div className="panel-title"><div><span className="admin-kicker">ORGANIZER ACTIONS</span><h2>Audit log</h2></div></div><div className="table-wrap"><table><thead><tr><th>TIME</th><th>ACTION</th><th>TARGET</th><th>DETAILS</th></tr></thead><tbody>{audit.map(a=><tr key={a.id}><td>{a.createdAt}</td><td>{a.action}</td><td>{a.target || "—"}</td><td><code>{JSON.stringify(a.metadata)}</code></td></tr>)}</tbody></table></div></>}
    </main><footer className="admin-footer">FARMCRAFT · SHARED ARENA SERVICES <span>LAST REFRESH {new Date().toLocaleTimeString()}</span></footer></div>;
}

function awaitSafeJobs(jobs, data) { return jobs.filter(x=>x.status==="failed").length ? jobs.filter(x=>x.status==="failed") : (data?.recentFailures || []); }
function Metric({ label, value, hint }) { return <div className="metric-card"><span>{label}</span><b>{value ?? "—"}</b>{hint&&<small>{hint}</small>}</div>; }
function StatusRow({ name, status, value }) { return <div className="status-row"><span className={`status-dot ${String(status).toLowerCase()}`}/><b>{name}</b><em>{value || String(status).toUpperCase()}</em></div>; }
function JobDetail({ job, onBack, onRetry, onCancel }) { return <section className="admin-panel"><button className="quiet-button" onClick={onBack}>← All jobs</button><div className="panel-title"><h2>{job.type} · {job.id.slice(0,8)}</h2><span className={`state ${job.status}`}>{job.status}</span></div><div className="detail-grid">{[["Team",job.team],["Submission",job.submissionId],["Created",job.createdAt],["Started",job.startedAt],["Completed",job.completedAt],["Worker",job.worker],["Opponent",job.opponent],["Seed",job.seed],["Queue wait",job.queueWaitSeconds == null ? "—" : `${job.queueWaitSeconds}s`],["Runtime",job.runtimeSeconds == null ? "—" : `${job.runtimeSeconds}s`],["Progress",job.progressTotal?`${job.progressCurrent}/${job.progressTotal}`:"—"],["Attempts / retries",`${job.attempts} / ${job.retryCount}`],["Failure class",job.errorKind],["Error",job.error]].map(([k,v])=><div key={k}><small>{k}</small><b>{v ?? "—"}</b></div>)}</div>{job.status==="failed"&&["ENGINE_FAILURE","WORKER_FAILURE","DATABASE_FAILURE","REDIS_FAILURE","STORAGE_FAILURE","INFRASTRUCTURE_TIMEOUT","infrastructure"].includes(job.errorKind)&&<button className="primary-action" onClick={onRetry}>Retry infrastructure failure</button>}{job.status==="queued"&&<button className="danger-button" onClick={onCancel}>Cancel queued job</button>}</section>; }
