export const STRATEGY_MISSIONS = [
  { id: "core", level: 1, branch: "Core", title: "Working Farmer", unlock: "always", concept: "Reliable movement, planting, watering, harvesting and selling.", problem: "A strategy cannot improve until every basic action completes safely.", hint: "Build a clear fallback order for useful work.", prompt: "My FarmCraft agent has basic actions but sometimes wastes turns. Review only its action priority and add a safe fallback order. Explain each priority before changing code." },
  { id: "crop_economics", level: 2, branch: "Economy", title: "Crop Economist", unlock: "core", concept: "Compare seed cost, expected yield, price and cycle duration.", problem: "The highest current price may still produce poor value over time.", hint: "Compare crops with a shared economic unit without hardcoding a winner.", prompt: "My farming bot chooses crops mainly from current selling price. Improve only crop selection so it compares seed cost, expected yield, crop duration, current price and current day. Explain the reasoning first." },
  { id: "market", level: 3, branch: "Market Mastery", title: "Market Forecaster", unlock: "crop_economics", concept: "Reason about dynamic prices and supply already on the way.", problem: "A profitable crop can collapse in value before harvest.", hint: "Estimate supply from planted crops before committing again.", prompt: "My bot plants too much when the current price is high. Use market inventory, crops already planted and expected yield to estimate future supply before choosing a crop. Change only the forecast and crop score." },
  { id: "workforce", level: 4, branch: "Workforce", title: "Workforce Manager", unlock: "sandbox", concept: "Balance job value, travel, deadlines and worker coordination.", problem: "More workers do not help when they walk too far or duplicate tasks.", hint: "Let urgency grow near deadlines while preserving economic value.", prompt: "My workers choose jobs mostly by importance and spend too much time walking. Improve job scoring with Manhattan distance and time-dependent urgency. Do not rewrite the scheduler." },
  { id: "capital", level: 5, branch: "Economy", title: "Capital Allocator", unlock: "crop_economics", concept: "Reserve cash while comparing workers, land and inventory investments.", problem: "Aggressive spending can leave the farm unable to buy essentials.", hint: "Treat the reserve as configurable and allow exceptional investments.", prompt: "My bot sometimes spends almost all its money and cannot buy feed or seeds. Add a configurable cash reserve to market decisions while still allowing unusually valuable investments." },
  { id: "livestock", level: 6, branch: "Livestock", title: "Livestock Economy", unlock: "sandbox", concept: "Model animal return, feed, structures and daily logistics.", problem: "Animals create recurring value but also recurring obligations.", hint: "Start with one animal loop and measure its workload.", prompt: "Add one modest livestock strategy to my bot. Account for structure cost, feed, daily care, harvest logistics and available workers. Keep crop behavior intact." },
  { id: "trading", level: 7, branch: "Market Mastery", title: "Strategic Trader", unlock: "market", concept: "Choose when and how much to sell under storage and price pressure.", problem: "Selling everything can crash price; holding everything can waste the season.", hint: "Examine the value of the next unit sold.", prompt: "My bot sells too much product at once. Estimate the price after selling additional units and stop when further selling becomes unattractive. Include storage pressure and endgame urgency." },
  { id: "opponent", level: 8, branch: "Intelligence", title: "Opponent Intelligence", unlock: "market", concept: "Include the visible rival farm in market expectations.", problem: "Both farms contribute to future shared supply.", hint: "Observe composition rather than countering one named crop.", prompt: "My bot predicts supply from its own farm. Extend the forecast to include visible opponent crops without hardcoding one crop or directly copying the opponent." },
  { id: "optimizer", level: 9, branch: "Advanced", title: "Adaptive Optimizer", unlock: "advanced", concept: "Adapt workload, triage and liquidation to the remaining season.", problem: "A fixed plan fails when capacity, prices or remaining time change.", hint: "Switch modes from measured signals, not fixed scripts.", prompt: "Help my bot detect workload overload and enter a triage mode. Prioritize expiring, urgent and endgame work using existing telemetry. Keep the strategy configurable." },
];

export function missionUnlocked(mission, summary) {
  if (mission.unlock === "always") return true;
  if (mission.unlock === "sandbox") return (summary?.sandboxRunCount || 0) > 0;
  if (mission.unlock === "advanced") return (summary?.sandboxRunCount || 0) >= 3;
  return Boolean(summary?.capabilities?.find((item) => item.id === mission.unlock)?.detected);
}
